import { useState } from 'react';
import { Link } from 'react-router-dom';
import { useApp } from '../context/AppContext';

function TeacherGameStudio() {
    const { games, addGame, classes, assignGameToClass } = useApp();
    const [prompt, setPrompt] = useState('');
    const [isGenerating, setIsGenerating] = useState(false);
    const [generatedGame, setGeneratedGame] = useState(null);

    const handleGenerate = () => {
        if (!prompt) return;
        setIsGenerating(true);

        // Simulated Gemini Response: A simple playable "Click the Verb" game
        const playableGameCode = `
            <!DOCTYPE html>
            <html>
            <head>
                <style>
                    body { font-family: sans-serif; text-align: center; background: #f0fdf4; padding: 20px; }
                    .word { font-size: 24px; font-weight: bold; color: #15803d; margin: 20px; }
                    button { padding: 10px 20px; font-size: 18px; background: #16a34a; color: white; border: none; border-radius: 8px; cursor: pointer; }
                    button:hover { background: #15803d; }
                    .score { font-size: 18px; color: #555; margin-bottom: 20px; }
                </style>
            </head>
            <body>
                <h1>🇪🇸 Verbo Clicker</h1>
                <p>Click the button when you see a VERB!</p>
                <div class="score">Score: <span id="score">0</span></div>
                <div id="word-display" class="word">...</div>
                <button onclick="checkWord()">It's a Verb!</button>

                <script>
                    const words = [
                        { text: "Correr (Run)", isVerb: true },
                        { text: "Gato (Cat)", isVerb: false },
                        { text: "Comer (Eat)", isVerb: true },
                        { text: "Casa (House)", isVerb: false },
                        { text: "Saltar (Jump)", isVerb: true }
                    ];
                    let currentWord = {};
                    let score = 0;

                    function nextWord() {
                        const randomIndex = Math.floor(Math.random() * words.length);
                        currentWord = words[randomIndex];
                        document.getElementById('word-display').innerText = currentWord.text;
                    }

                    function checkWord() {
                        if (currentWord.isVerb) {
                            score += 10;
                            alert("¡Correcto! +10 Puntos");
                        } else {
                            score -= 5;
                            alert("¡Incorrecto! Try again.");
                        }
                        document.getElementById('score').innerText = score;
                        nextWord();
                    }

                    nextWord();
                </script>
            </body>
            </html>
        `;

        // Mock Gemini API call
        setTimeout(() => {
            setGeneratedGame({
                title: "Generated: " + prompt,
                content: playableGameCode
            });
            setIsGenerating(false);
        }, 1500);
    };

    const saveGame = () => {
        if (!generatedGame) return;
        addGame({
            title: "Custom Game: " + prompt.substring(0, 15) + "...",
            description: "Generated by Gemini",
            type: 'Custom',
            content: generatedGame.content
        });
        setGeneratedGame(null);
        setPrompt('');
        alert("Game Saved! / Juego Guardado!");
    };
    /* Assignment State */
    const [assigningGame, setAssigningGame] = useState(null);
    const handleAssign = (classId) => {
        assignGameToClass(assigningGame.id, classId);
        alert(`Game "${assigningGame.title}" assigned!`);
        setAssigningGame(null);
    }

    return (
        <div className="min-h-screen bg-brand-cream p-8">
            <header className="mb-10 flex justify-between items-center">
                <div>
                    <Link to="/" className="text-sm font-bold text-brand-blue hover:underline mb-2 block">← Back to Dashboard</Link>
                    <h1 className="text-4xl font-extrabold text-brand-blue tracking-tight">Gemini Game Studio</h1>
                    <p className="text-slate-500 mt-2 text-lg">Create custom games with AI magic. / Crea juegos con magia IA.</p>
                </div>
            </header>

            {/* Creator Section */}
            <div className="card mb-12 border-2 border-brand-blue/10">
                <h2 className="text-2xl font-bold text-slate-800 mb-4 flex items-center gap-2">
                    ✨ Create New Game / Crear Nuevo Juego
                </h2>
                <div className="flex flex-col md:flex-row gap-4">
                    <input
                        className="input-field flex-1"
                        placeholder="Describe the game... (e.g. 'A quiz about colors in Spanish')"
                        value={prompt}
                        onChange={(e) => setPrompt(e.target.value)}
                    />
                    <button
                        onClick={handleGenerate}
                        disabled={isGenerating}
                        className={`btn-primary bg-gradient-to-r from-brand-blue to-purple-600 ${isGenerating ? 'opacity-70 cursor-wait' : ''}`}
                    >
                        {isGenerating ? 'Generating... 🤖' : 'Ask Gemini 🪄'}
                    </button>
                </div>

                {/* Preview Area (Mock) */}
                {generatedGame && (
                    <div className="mt-8 bg-slate-900 rounded-xl p-4 animate-fade-in">
                        <div className="flex justify-between items-center mb-4 text-white">
                            <h3 className="font-bold">Preview: {generatedGame.title}</h3>
                            <div className="flex gap-2">
                                <button onClick={() => setGeneratedGame(null)} className="text-sm text-slate-400 hover:text-white mr-4">Discard</button>
                                <button onClick={saveGame} className="btn-accent py-2 px-4 text-sm">Save & Assign 💾</button>
                            </div>
                        </div>
                        <div className="bg-white rounded-lg overflow-hidden border-2 border-slate-200">
                            <iframe
                                title="Game Preview"
                                srcDoc={generatedGame.content}
                                className="w-full h-80"
                            />
                        </div>
                    </div>
                )}
            </div>

            {/* My Games List */}
            <h2 className="text-2xl font-bold text-slate-800 mb-6">📚 My Library / Mi Biblioteca</h2>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                {games.map((game) => (
                    <div key={game.id} className="card group hover:-translate-y-1 bg-white">
                        <div className="flex justify-between items-start mb-4">
                            <div className="bg-brand-green/20 p-3 rounded-full text-brand-green">
                                <span className="text-2xl">🎮</span>
                            </div>
                            <span className="text-xs font-bold text-slate-400 bg-slate-100 px-2 py-1 rounded-full">{game.type}</span>
                        </div>
                        <h3 className="text-xl font-bold text-brand-text mb-2">{game.title}</h3>
                        <p className="text-slate-400 text-sm mb-4">{game.description}</p>
                        <button
                            onClick={() => setAssigningGame(game)}
                            className="w-full btn-secondary text-sm py-2"
                        >
                            Assign to Class ➜
                        </button>
                    </div>
                ))}
            </div>

            {/* Assignment Modal */}
            {assigningGame && (
                <div className="fixed inset-0 bg-slate-900/50 backdrop-blur-sm flex justify-center items-center z-50 animate-fade-in">
                    <div className="bg-white rounded-2xl p-8 w-full max-w-sm shadow-2xl animate-pop-in">
                        <h3 className="text-xl font-bold text-brand-text mb-4">Assign "{assigningGame.title}"</h3>
                        <p className="text-slate-500 mb-4 text-sm">Select a class to assign this game to:</p>
                        <div className="space-y-2">
                            {classes.length === 0 && <p className="text-sm text-slate-400 italic">No classes yet. Create one on the dashboard!</p>}
                            {classes.map(cls => (
                                <button
                                    key={cls.id}
                                    onClick={() => handleAssign(cls.id)}
                                    className="w-full text-left p-3 rounded-lg hover:bg-brand-cream border border-transparent hover:border-brand-blue/30 transition-colors font-medium text-slate-700"
                                >
                                    🏫 {cls.name}
                                </button>
                            ))}
                        </div>
                        <button
                            onClick={() => setAssigningGame(null)}
                            className="mt-6 w-full text-slate-400 hover:text-slate-600 text-sm font-bold"
                        >
                            Cancel
                        </button>
                    </div>
                </div>
            )}
        </div>
    );
}

export default TeacherGameStudio;
